import Head from 'next/head'
import { FormSearch } from '../components/FormSearch'
import { Navbar } from '../components/Navbar'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`w-full bg-cover bg-center min-h-screen flex flex-col items-center bg-[url('../public/images/ufpe.jpg')]`}>
        <Navbar/>
        <FormSearch label ={"Digite o nome do pesquisador:"} placeholder={"Buscar pesquisador"}/>
        
      </main>
    </>
  )
}
