import Head from "next/head"
import { FormSearch } from "../../components/FormSearch"
import { Navbar } from "../../components/Navbar"
import { Researcher } from "../../components/Researcher"
import { useEffect, useState } from "react";

export default function BuscaNome(){
  const [isClicked, setClicked] = useState(false)

  const handleSubmit = () =>{
      isClicked === false && setClicked(true)
      isClicked === false && console.log(isClicked)
      isClicked === true && console.log(isClicked)
      isClicked === true && setClicked(false)
    }
    return(
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`w-full min-h-screen flex flex-col bg-cover bg-center bg-imagem  lg:overflow-x-hidden `}>
        <Navbar/>  
        <div className="flex flex-col max-h-11/12 justify-center items-center mt-10">
          <FormSearch label={'Buscar Pesquisadores'} placeholder={'Copie e cole a lista de nomes dos pesquisadores...'} submit={()=> handleSubmit}/>
          {isClicked === true && <div className="flex flex-col w-4/6  p-6">
            <h1 className="text-white text-3xl mb-6 drop-shadow-md">Pesquisadores que possuem vínculo com a UFPE:</h1>
            <div className="grid grid-rows-4">
              <Researcher/>
              <Researcher/>
            </div>
          </div>}
        </div>
      </main>
    </>
    )
}