import Head from "next/head"
import { FormSearch } from "../../components/FormSearch"
import { Navbar } from "../../components/Navbar"
import { Researcher } from "../../components/Researcher"
import { useEffect, useState } from "react";
import BuscaNomeType from "../../components/FormSearch/BuscaNomeType";
import Image from "next/image";
import { InfoModal } from "../../components/modal";


const BuscaNome = (props:BuscaNomeType) =>{
  const [isClicked, setClicked] = useState(false)
  const [isClickedInfo, setClickedInfo] = useState(false)
  const [ListResearcher, setListResearcher] = useState<{NOME:string, EMAIL_PRINCIPAL:string, EMAIL_SECUNDARIO:string, DEPARTAMENTO:string, CENTRO:string }[]>([])
  const [error, setError]= useState()
  const [opacity, setOpacity] = useState('')

  //const ListResearcher = ["Pedro Valadão Carelli", 'Alfredo Macedo Gomes', "Joaquim Martins Filho", "Ranilson Filho Martins"]
  
  return(
        <>
      <Head>
        <title>SisPesq - DPQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`w-full font-Roboto min-h-screen flex flex-col bg-imagem bg-cover bg-center bg-fixed  lg:overflow-x-hidden `}>
        <Navbar/>  
       
        <div className="flex flex-col max-h-11/12 justify-center items-center mt-40">
          {isClicked === false && <FormSearch label={'Buscar Pesquisadores'} placeholder={'Copie e cole a lista de nomes dos pesquisadores...'}  isClicked ={isClicked} setClicked = {setClicked} ListResearcher = {ListResearcher} setListResearcher = {setListResearcher} error= {error} setError = {setError} isClickedInfo={isClickedInfo} setClickedInfo={setClickedInfo} opacity={opacity} setOpacity={setOpacity}/>}
          {isClicked === true && 
          <div className="flex flex-col w-11/12 lg:w-3/6  p-6">
            <div className="flex flex-col text-white text-lg lg:text-3xl mb-4 drop-shadow-md gap gap-6">
              Pesquisadores que possuem vínculo com a UFPE:
              <div className="border-b-2 border-red-500 w-full mb-6 bg-red-500"></div>
            </div>
            {ListResearcher.map((teacherName, index)=>(<Researcher key={index} nome={teacherName.NOME} emailPrincipal={teacherName.EMAIL_PRINCIPAL} emailSecundario={teacherName.EMAIL_SECUNDARIO} Centro={teacherName.CENTRO} Departamento={teacherName.DEPARTAMENTO}/>))}
            
          </div>}
          {isClicked ===true && ListResearcher.length===0 && <Image src={'/images/spin.gif'} alt="logo propesqi" width={100} height={50} className="ml-4"/>}
          {/*ListResearcher.length===0 && <p className="text-red-500 font-light">Desculpe. Nenhum Pesquisador da UFPE encontrado.</p> */}
        </div>
        {isClickedInfo === true && <InfoModal opacityBlur={opacity} setOpacityBlur={setOpacity} isClickedInfo = {isClickedInfo} setClickedInfo = {setClickedInfo}/>}
      </main>
    </>
    )
}

export default BuscaNome